<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elementByButtonFooter</name>
   <tag></tag>
   <elementGuidId>0d868d88-8fc4-402c-b444-2330af511813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer/div/div/div/button/div[contains(text(),&quot;${element}&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
