<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elementTagWithIndex</name>
   <tag></tag>
   <elementGuidId>72aca857-8217-4eca-8167-d567e722abd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//${elementTag}[@${elementParameter}=&quot;${elementValue}&quot;])[${elementIndex}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
