<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uniqueElementWithoutIndex</name>
   <tag></tag>
   <elementGuidId>29163529-f84b-4a00-a2f4-8a02b2b813a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//${elementTag}[@${elementParameter}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
