<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uniqueElement</name>
   <tag></tag>
   <elementGuidId>5e09df00-5b97-43cc-8b1c-e245a8ecf625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//${elementTag}[@${elementParameter}][${elementIndex}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
